language: android
env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - platform-tools
  - build-tools-25.0.1
  - android-25
  - extra-android-m2repository
script:
  - ./gradlew build 
before_install:
        - chmod +x gradlew
branches:
        only:
            - master
